### ISSUE TITLE
Split Photos and Videos into their own repository

### ISSUE THREAD

**Issue by phayes** [taibangle/awesome-china#1]
This is a fantastic project, thank you!

Cloning this repository in order to add a PR is a very resource intensive operation since it requires downloading all videos and images.  I would recommend creating a new `awesome-china-videos` and `awesome-china-images` (or maybe a single `awesome-china-media`) repository to hold videos and images, leaving this repository *mostly* text only to allow easier cloning and PR creation.

**Comment by MeiWithHongKong** [comment]
Great idea, will do!

**Comment by phayes** [comment]
Just a note that you'll have to rebase and force-push these changes since with a normal commit the files will still be in the history and therefore be downloaded on a clone.

**Comment by MeiWithHongKong** [comment]
Should be fixed now, thanks :)

**Comment by phayes** [comment]
Just cloned the new repo, very quick!   Thank you!
