### ISSUE TITLE
《南京条约》、《中英北京条约》、《展拓香港界址专条》

### ISSUE THREAD

**Issue by peachl** [taibangle/awesome-china#12]
凭什么说解放？发了那么多文献可以先了解一下上面的三个条约么？所谓的解放只是政权之间的斗争而已，你这种人就是被政权斗争所洗脑的。如果你觉得这个国家不好，那么应该想办法让它变得好起来（参与政界，用自己的能力给人民带来幸福），而不是暴动和嘴炮。暴动只是恐怖分子最擅长的手段。披着自由的旗子做着暴乱的事情，呵呵呵呵呵呵，真是有够恶心的。

**Comment by wysnxzm** [comment]
曱甴的自由是践踏在别人的自由之上

**Comment by MeiWithHongKong** [comment]
Those who make peaceful revolution impossible will make violent revolution inevitable.

**Comment by peachl** [comment]
你有什么资格提起革命？你凭什么提革命？告诉我谁赋予你革命的资格？参加过抗日战争？香港解放靠你？靠的是中华人民共和国。感觉你就和一个弱智的复读机一样复述着被洗脑的话。我以为git上面的人至少会讲道理。没想到你也和notepad++那个傻逼作者一样脑残。井底之蛙不过尔尔

**Comment by NicoleTYF** [comment]
@MeiWithHongKong Hey those people are just trolls from the Internet, their qq are being deleted when they talk about human right, you don't deserve their emotions with irrational brainwashed logic.

**Comment by wysnxzm** [comment]
> @MeiWithHongKong Hey those people are just trolls from the Internet, their qq are being deleted when they talk about human right, you don't deserve their emotions with irrational brainwashed logic.

你的人权就是践踏别人的人权哈哈哈笑掉大牙

**Comment by peachl** [comment]
> @MeiWithHongKong Hey those people are just trolls from the Internet, their qq are being deleted when they talk about human right, you don't deserve their emotions with irrational brainwashed logic.



> @MeiWithHongKong Hey those people are just trolls from the Internet, their qq are being deleted when they talk about human right, you don't deserve their emotions with irrational brainwashed logic.

废物，连自己的理论体系都没有败类。只会复制粘贴洗脑的暴徒。你也配谈自由？你们这些垃圾对自由有过什么贡献？游行示威？破坏秩序？罢工罢课？你们对这个社会有什么有益的贡献？垃圾们？？？除了破坏你们还会什么？哦对了除了破坏你们还会草你们妈妈

**Comment by NicoleTYF** [comment]
wysnxsm 你常常說別人什麼什麼，你真的很喜歡使用人權呢，自由民主一定會很適合你。
@peachl 你冷靜一點哈哈哈哈，你們維權的qq被封號，習近平瞞著你們把經濟數據造假導致下一年經濟金融風暴，都就知道你沒有資格定義國際人權，人權至少可以互相給對方一個安全的說話空間。你可以先了解《中英聯合聲明》才來這裡言語暴力和嘴砲吧。

**Comment by NicoleTYF** [comment]
我覺得大家罵來罵去還是準備好下一年的經濟下滑吧，如果是學生就專心讀書吧，你們將來出來工作失業會令你們的父母擔心你的。

**Comment by peachl** [comment]
> wysnxsm 你常常說別人什麼什麼，你真的很喜歡使用人權呢，自由民主一定會很適合你。
> @peachl 你冷靜一點哈哈哈哈，你們維權的qq被封號，習近平瞞著你們把經濟數據造假導致下一年經濟金融風暴，都就知道你沒有資格定義國際人權，人權至少可以互相給對方一個安全的說話空間。你可以先了解《中英聯合聲明》才來這裡言語暴力和嘴砲吧。

安全的说话空间？现在你们的暴动导致香港是安全的么？比起我的言语你们在香港的暴动不是更加反人权？我至少没有破坏社会安定。不像某些败类。打着自由的旗号来宣扬暴行。对大陆不满就破坏你们自己的家园？还口口声声说人权？看看现在香港的样子，不是你们自己做的？

**Comment by peachl** [comment]
> 我覺得大家罵來罵去還是準備好下一年的經濟下滑吧，如果是學生就專心讀書吧，你們將來出來工作失業會令你們的父母擔心你的。

我可不像你这种Loser。我比你幸福的多。至少我爱我自己的祖国和家园。我没有主动去破坏他们。还有比起明年多担心担心自己，相比与你们这些恐怖分子所在的香港来说，大陆可太美好了。我倒是觉得香港的某些父母现在更担心他们的孩子，毕竟某大学已经被批捕了不少人

**Comment by wysnxzm** [comment]
> > 我覺得大家罵來罵去還是準備好下一年的經濟下滑吧，如果是學生就專心讀書吧，你們將來出來工作失業會令你們的父母擔心你的。
> 
> 我可不像你这种Loser。我比你幸福的多。至少我爱我自己的祖国和家园。我没有主动去破坏他们。还有比起明年多担心担心自己，相比与你们这些恐怖分子所在的香港来说，大陆可太美好了。我倒是觉得香港的某些父母现在更担心他们的孩子，毕竟某大学已经被批捕了不少人

曱甴还担心别人好搞笑,地铁被他们砸了路毁了学校毁了不担心担心自己被事后算账在这装圣母担心别人笑死了哈哈哈
现在全世界都在看他们的笑话,韩国日本英国学生全部撤离,日本发布警告
还不自知?不过也是,曱甴要是自知就不是曱甴了哈哈哈
还革命?你们的革命就是在商场吹空调,把厕所拉的臭气熏天,躲下水道逃命吗?哈哈哈哈哈哈

**Comment by wysnxzm** [comment]
> wysnxsm 你常常說別人什麼什麼，你真的很喜歡使用人權呢，自由民主一定會很適合你。
> @peachl 你冷靜一點哈哈哈哈，你們維權的qq被封號，習近平瞞著你們把經濟數據造假導致下一年經濟金融風暴，都就知道你沒有資格定義國際人權，人權至少可以互相給對方一個安全的說話空間。你可以先了解《中英聯合聲明》才來這裡言語暴力和嘴砲吧。

您的人权就是把反对者当街焚烧,把无辜大伯用砖头砸死?
等着秋后算账吧曱甴

**Comment by NicoleTYF** [comment]
wysnxsm 曱甴和在一起就是簡體字的國字。

@peachl 你問那麼多問題就知道你根本沒有關心過香港發生的事，香港的不滿是由2008年忍到現在，你由[梁啟智的《香港第一課》](https://matters.news/@leungkaichihk/%E9%A6%99%E6%B8%AF%E7%AC%AC%E4%B8%80%E8%AA%B2-%E7%B0%A1%E4%BB%8B%E5%8F%8A%E7%9B%AE%E9%8C%84-zdpuB2J818r8yUSDeZ4vDARrnQ4ut3S2UYjALXHJ16jp25w4P)了解吧，他是寫給大陸學生的，我朋友也說把中港矛盾解釋的挺好的。
香港那示威其實就是因為沒有暴動啊，你們牆內看到的是政府要左派媒體做的一場抹黑活動，就像俄羅斯抹黑美國總統選舉那樣。白講成黑，就當新聞了（機場女護被布袋彈射爆眼，做得是的是警察，你覺得誰會有槍呢？）

幸不幸福你經歷明年的經濟你就親眼看到了。
比言語你們簡直就是反人類了，你想想，你們有14億人吧，『Loser』『恐怖分子』『曱甴』網路暴力在乘14億的暴力就是你們的暴力。

**Comment by NicoleTYF** [comment]
wysnxsm 人權是什麼，這是中國在聯合國承認的國際人權公約[《世界人权宣言》](https://www.ohchr.org/EN/UDHR/Documents/UDHR_Translations/chn.pdf)

**Comment by wysnxzm** [comment]
> wysnxsm 曱甴和在一起就是簡體字的國字。
> 
> @peachl 你問那麼多問題就知道你根本沒有關心過香港發生的事，香港的不滿是由2008年忍到現在，你由[梁啟智的《香港第一課》](https://matters.news/@leungkaichihk/%E9%A6%99%E6%B8%AF%E7%AC%AC%E4%B8%80%E8%AA%B2-%E7%B0%A1%E4%BB%8B%E5%8F%8A%E7%9B%AE%E9%8C%84-zdpuB2J818r8yUSDeZ4vDARrnQ4ut3S2UYjALXHJ16jp25w4P)了解吧，他是寫給大陸學生的，我朋友也說把中港矛盾解釋的挺好的。
> 香港那示威其實就是因為沒有暴動啊，你們牆內看到的是政府要左派媒體做的一場抹黑活動，就像俄羅斯抹黑美國總統選舉那樣。白講成黑，就當新聞了（機場女護被布袋彈射爆眼，做得是的是警察，你覺得誰會有槍呢？）
> 
> 幸不幸福你經歷明年的經濟你就親眼看到了。
> 比言語你們簡直就是反人類了，你想想，你們有14億人吧，『Loser』『恐怖分子』『曱甴』網路暴力在乘14億的暴力就是你們的暴力。

国和曱甴 你的脑子是怎么抽象到一起的?
还记得你们曱甴两次亡国吗,第一次因为商场关了冷气亡国,第二次因为厕所太臭亡国
可把我乐死了,就连逃跑都嫌下水道太臭而束手就擒,这就是你们的"勇士""革命者"?回家吃奶去吧
一群被自由民主洗脑的憨憨,自以为高人一等实则贱民一群

**Comment by NicoleTYF** [comment]
wysnxzm 大陸網友發的, 他們挺喜歡黑別人的.

**Comment by peachl** [comment]
> wysnxsm 曱甴和在一起就是簡體字的國字。
> 
> @peachl 你問那麼多問題就知道你根本沒有關心過香港發生的事，香港的不滿是由2008年忍到現在，你由[梁啟智的《香港第一課》](https://matters.news/@leungkaichihk/%E9%A6%99%E6%B8%AF%E7%AC%AC%E4%B8%80%E8%AA%B2-%E7%B0%A1%E4%BB%8B%E5%8F%8A%E7%9B%AE%E9%8C%84-zdpuB2J818r8yUSDeZ4vDARrnQ4ut3S2UYjALXHJ16jp25w4P)了解吧，他是寫給大陸學生的，我朋友也說把中港矛盾解釋的挺好的。
> 香港那示威其實就是因為沒有暴動啊，你們牆內看到的是政府要左派媒體做的一場抹黑活動，就像俄羅斯抹黑美國總統選舉那樣。白講成黑，就當新聞了（機場女護被布袋彈射爆眼，做得是的是警察，你覺得誰會有槍呢？）
> 
> 幸不幸福你經歷明年的經濟你就親眼看到了。
> 比言語你們簡直就是反人類了，你想想，你們有14億人吧，『Loser』『恐怖分子』『曱甴』網路暴力在乘14億的暴力就是你們的暴力。

你知道什么叫割让么？知道什么叫不平等条约么？意思是我打了你一顿再把你老婆抢了，然后你老婆就是我的了？还有我觉得说你们是恐怖分子和曱甴是事实，不是网络暴力。一个正常的人，如果觉得政体不公，那么他应该去从政，用正当的方式去改变某些东西。而不是在自家无能狂怒。打砸抢烧、扰乱公共秩序，所以我说你们是Loser。比起说我言语暴力我觉得你们的肢解自己的家园更暴力。因为恐怖分子的本质就是破坏，而不是努力。

**Comment by wysnxzm** [comment]
https://wx1.sinaimg.cn/mw690/6232a59agy1g94fo4623lj20h40juqgz.jpg


> wysnxzm 大陸網友發的, 他們挺喜歡黑別人的, 服了你們的想像力.

看看https://wx1.sinaimg.cn/mw690/6232a59agy1g94fo4623lj20h40juqgz.jpg
爬进下水道逃跑,跑不了报警求助,你可以说是污蔑虚假咯反正你们活在自己的世界
洋教官,拿薪酬你以为我们都不知道吗?表面革命实则赚钱,又当又立婊子不如

**Comment by NicoleTYF** [comment]
你看誰是假新聞，那比起你先在的住所跟我的住所，那個會更清楚香港的情勢？
那你跟那些香港叫蝗蟲的人不是網路暴力沒分別 , 輸打贏要. 
@peachl 你也配姓趙? 你覺得你國對其他國種族的不平等條約會跟你說嗎？你對網路暴力的合理化是更加襯托中國2008年來對我們的態度。

**Comment by NicoleTYF** [comment]
wysnxsm 你可以看你由梁啟智寫的[《香港第一課》](https://matters.news/@leungkaichihk/%E9%A6%99%E6%B8%AF%E7%AC%AC%E4%B8%80%E8%AA%B2-%E7%B0%A1%E4%BB%8B%E5%8F%8A%E7%9B%AE%E9%8C%84-zdpuB2J818r8yUSDeZ4vDARrnQ4ut3S2UYjALXHJ16jp25w4P)了解香港人的想法吧，我也覺得挺客觀的。

**Comment by peachl** [comment]
> 你看誰是假新聞，那比起你先在的住所跟我的住所，那個會更清楚香港的情勢？
> 那你跟那些香港叫蝗蟲的人不是網路暴力沒分別 , 輸打贏要.
> @peachl 你也配姓趙? 你覺得你國對其他國種族的不平等條約會跟你說嗎？你愛國，還是國家內的人？你對網路暴力的合理化是更加襯托中國2008年來對我們的態度。

那你倒是找出来一条我国对其他国家签订让他们割让香港的不平等条约？你凭什么认为香港是个国家？还有看看wiki上面对香港的描述——中华人民共和国特别行政区之一。还有我也不稀罕姓赵，你这种人总是喜欢偷换概念。我问你的是我是不是打了你一顿把你老婆抢了，你老婆就是我的了。又不敢直接回答我的问题。难道废青们的表达能力这么成问题么？果然头脑简单，一句话别人都可以怂恿你们。还有你们美国爸爸貌似在访谈中也称你们的行为是暴动。虽然后面反水了。

**Comment by peachl** [comment]
> 你看誰是假新聞，那比起你先在的住所跟我的住所，那個會更清楚香港的情勢？
> 那你跟那些香港叫蝗蟲的人不是網路暴力沒分別 , 輸打贏要.
> @peachl 你也配姓趙? 你覺得你國對其他國種族的不平等條約會跟你說嗎？你愛國，還是國家內的人？你對網路暴力的合理化是更加襯托中國2008年來對我們的態度。

从大秦开始香港就是秦朝领土，你在这里和我扯什么扯？意思你要自称是百越部落遗孤？自己独立成国？不肖子孙。历史学好了么？学不好别在这里和我扯。被外国人管辖一段时间就觉得自己是个国家了？你以为英国凭什么把主权还回来？真是够贱的。把你从殖民地的台阶上拉起来。你还要跪下去。

**Comment by NicoleTYF** [comment]
@peachl 你留錯留言區言啦，我沒說什麼香港國家甚麼的，你是在回另一個用家嗎？但我聽到大陸的朋友也是對港獨亂定義的，在大陸網積非成是。

**Comment by peachl** [comment]
> @peachl 你留錯留言區啦，我沒說什麼香港國家甚麼的你就扣帽子，你是在回另一個用家嗎？但我聽到大陸的朋友也是對港獨亂定義的，在大陸網積非成是。

我否定这个项目的发起人就是因为他表示港独，你过来叫嚣助场，然后说我扣帽子？更有意思的是作为一个逻辑思维严谨的开发人员在git上面据然还会使用“我听到”这种开头的词汇。那我可不可以这样说“我听到全世界都在说香港人现在的行为是暴乱和恐怖活动”，“我听说全世界的人民都承认香港是我国的特别行政区”。表达能力堪忧，判断方式依据自己听说的。还说国内消息闭塞。真正消息闭塞的到底是谁呢

**Comment by NicoleTYF** [comment]
@peachl 香港人跟你說，香港在清朝以前是沒有名字的，晚清前的時代還沒有用民族做國家單位的概念，也沒有用條約定邊界的方法。大概180年前香港在大清跟外國出入口是才有人叫『香港』，是中西方商人的彙集點。

**Comment by wysnxzm** [comment]
> @peachl 你留錯留言區啦，我沒說什麼香港國家甚麼的你就扣帽子，你是在回另一個用家嗎？但我聽到大陸的朋友也是對港獨亂定義的，在大陸網積非成是。

如今，美国加州人民也玩起了“脱美”运动。计划在2020年美国大选后举行一次全民公投，大家希望能把加利福尼亚州从美国分离出来。独立后的加州将成为世界第六大经济体，经济比法国强大，人口比波兰多。 “脱美”倡议得到了香港废青们的反对，废青希望当地民众能够冷静思考，不要冲动行事。而当地脱美组织者则对香港废青的态度表示失望… （此信息获取于特殊网络媒介，FB等主流平台均已封锁消息）

为什么你们可以革命却要护全美国爸爸呢?你们很有被当枪使的自觉啊!

**Comment by peachl** [comment]
> @peachl 香港人跟你說，香港在清朝以前是沒有名字的，晚清前的時代還沒有用民族做國家單位的概念，也沒有用條約定邊界的方法。大概180年前香港在大清跟外國出入口是才有人叫『香港』，是中西方商人的彙集點。

作为一个思考方式正常的人。居然可以拿名字作为推脱？？？？那我今天杀了人，然后改了名字。是不是就和我无关呢？香港没名字所以以前都不算，从有了名字那么就可以另立国家了，你是小学生么？这种道理你都好意思说出口？？？拜托你回复我的时候可以麻烦正面回答一下我的问题么？还是说对我的问题都哑口无言？

**Comment by NicoleTYF** [comment]
@peachl 所以就叫你看梁啟智寫的[《香港第一課》](https://matters.news/@leungkaichihk/%E9%A6%99%E6%B8%AF%E7%AC%AC%E4%B8%80%E8%AA%B2-%E7%B0%A1%E4%BB%8B%E5%8F%8A%E7%9B%AE%E9%8C%84-zdpuB2J818r8yUSDeZ4vDARrnQ4ut3S2UYjALXHJ16jp25w4P)
我也希望你們冷靜一下想，你們身邊的人是怕不愛國，還是真的愛國家的人？

**Comment by wysnxzm** [comment]
> @peachl 所以就叫你看梁啟智寫的[《香港第一課》](https://matters.news/@leungkaichihk/%E9%A6%99%E6%B8%AF%E7%AC%AC%E4%B8%80%E8%AA%B2-%E7%B0%A1%E4%BB%8B%E5%8F%8A%E7%9B%AE%E9%8C%84-zdpuB2J818r8yUSDeZ4vDARrnQ4ut3S2UYjALXHJ16jp25w4P)，你很想要答案似的（很多？？？）就在這裡找吧，黨一個小問題也平息不到你的怨氣就知道國家有多『強大』，是民怨四起。
> 我也希望你們冷靜一下想，你們身邊的人是怕不愛國，還是真的愛國家的人？

正面问题不回答,一说暴力罪行就用"流血革命"推脱
一问就是香港被压迫没有自由,国家用最好的政策和资源输血养出你们这群白眼狼你知道你们每天喝的水都是大陆运过去的吗?要是想治你们有千万种方法,轻轻一捏曱甴就爆了
你要追求自由就游到美帝啊,可惜人家也不要你.讲真的,你们曱甴全都跳海想去哪里追求自由都没问题
我们只要地,不要垃圾人不要光会喊口号打砸抢烧破坏和平的人你们一点正面价值都没有
人在做,天在看,因果报应循环不爽哈哈哈

**Comment by NicoleTYF** [comment]
wysnxzm 因為你們兩個一起留言，我看來是沒看到一些的。所以說你們冷靜一點啊。

**Comment by NicoleTYF** [comment]
wysnxzm 而且我給你的書，你有看嗎？

**Comment by peachl** [comment]
> @peachl 所以就叫你看梁啟智寫的[《香港第一課》](https://matters.news/@leungkaichihk/%E9%A6%99%E6%B8%AF%E7%AC%AC%E4%B8%80%E8%AA%B2-%E7%B0%A1%E4%BB%8B%E5%8F%8A%E7%9B%AE%E9%8C%84-zdpuB2J818r8yUSDeZ4vDARrnQ4ut3S2UYjALXHJ16jp25w4P)
> 我也希望你們冷靜一下想，你們身邊的人是怕不愛國，還是真的愛國家的人？

谁列举谁举例这个辩论中最重要的知识你都不明白了。你的意思是我可以说我说的都对，然后让你自己去书里面找我说的对的东西吧。只要被人驳倒了就让别人去看书，可以找个好点的理由推脱么。并且我觉得我自己特别喜欢这个国家。所以我没必要质疑其他人是不是真的爱国与否。因为你们生在这种地方已经被洗脑过了所以就只会不断的质疑中国。就和日本人右翼从来不承认南京大屠杀一样。你们和他们一模一样。还有你们的表达能力真的堪忧，一个是个只会复制粘贴的人，另一个只会让人看书。作为同样是中国人，果然一国两智。

**Comment by NicoleTYF** [comment]
你開一個issue來是辯論，你的質詢都在牆內外隔絕，兩岸沒有同一資訊基礎，例如連人權自由在大陸網路被污名化一事都不知道就來『辯論』，還叫人廢青Loser，給我的感覺你這是叫謾罵吧。
我們沒有說什麼『流血革命』，是你們大陸人山人海中積非成是的字吧。

**Comment by NicoleTYF** [comment]
@peachl 你上課在政治課有沒有問過為什麼課室有『不談政治』的。

**Comment by peachl** [comment]
> 你開一個issue來是辯論，你的質詢都在牆內外隔絕，兩岸沒有同一資訊基礎，例如連人權自由在大陸網路被污名化一事都不知道就來『辯論』，還叫人廢青Loser，給我的感覺你這是叫謾罵吧。
> 我們沒有說什麼『流血革命』那麼誇大的東西，是你們大陸人山人海中積非成是的字吧。

现在香港是不是有暴乱？是不是有打砸抢烧的人？我也没说你流血革命，更好笑的是，有人妄图分裂你的祖国，你还能对他很温柔的说话？要不你老婆借我使使？我只知道对好人温柔，而不是你们这种活在封闭世界，还叫嚣分裂祖国的人。你见过这个项目发起人说什么了么？他或许现在特开心，毕竟随便发个东西都能让中国人吵起来。你和他，一个蠢一个坏。不幸的是你是蠢的那个。被人驳倒体无完肤也没人帮你，只有你自己在这里转移话题。真可悲。

**Comment by NicoleTYF** [comment]
你在說什麼，你的想像力很大，牆禁了很多東西所以沒人用邏輯答到你的問題只可以司空妄想吧。我當然可以一個個答你，但你們原來是來罵人『蠢』『可悲』『Loser』，我祝福你們罵人的東西會發生你們身上。

**Comment by wysnxzm** [comment]
> 现在香港是不是有暴乱？是不是有打砸抢烧的人？我也没说你流血革命，更好笑的是，有人妄图分裂你的祖国，你还能对他很温柔的说话？要不你老婆借我使使？我只知道对好人温柔，而不是你们这种活在封闭世界，还叫嚣分裂祖国的人。你见过这个项目发起人说什么了么？他或许现在特开心，毕竟随便发个东西都能让中国人吵起来。你和他，一个蠢一个坏。不幸的是你是蠢的那个。被人驳倒体无完肤也没人帮你，只有你自己在这里转移话题。真可悲。

这种人要么蠢要么坏要么二者皆有,现在就指望着曱甴的笑话活着了哈哈哈

**Comment by NicoleTYF** [comment]
wysnxzm 我祝福你說別人的東西會發生你身上。((或者是已經發生了？

**Comment by NicoleTYF** [comment]
甴近平的笑话活着

**Comment by NicoleTYF** [comment]
我轉自這個project作者的動機：
The purpose of the repo is not to spread lies and misinformation, or to insult the Chinese people. Most of the content is taken from Wikipedia, which is arguable the most reputable and least biased source you can find, as all the content in the article has to be sourced (with sources that can be verified or have high credibility). I could've posted articles that paint CCP in a much worse light, but I didn't, because I only want to share truthful information.

If you come here to post lies, misinformation, whataboutism or death threats, then don’t expect a serious discussion. If you believe the content contain false information, or wish to discuss what’s happening in Xinjiang, Hong Kong, Tibet, etc. then you’re welcome to do so, but please act in good faith.

**Comment by peachl** [comment]
> 你在說什麼，你的想像力很大，牆禁了很多東西所以沒人用邏輯答到你的問題只可以司空妄想吧。我當然可以一個個答你，但你們原來是來罵人『蠢』『可悲』『Loser』，我祝福你們罵人的東西會發生你們身上。

**Comment by wysnxzm** [comment]
> wysnxzm 我祝福你說別人的東西會發生你身上。((或者是已經發生了？

嗨,对于暴徒的任何诋毁我表示毫不在意
谁会在意一只曱甴的反抗呢?你得感谢有海关的存在,要不然第一天你们就被会丢进海里喂鱼
活在阴影下的宵小而已,连"革命"都不敢露出真面目,曱甴你们当之无愧
如果你们认为自己是正义的,为什么要把真面目隐藏在口罩之下?只有曱甴才见不得光不是吗

**Comment by NicoleTYF** [comment]
我祝福你在以後面說香港示威者的東西會發生你身上。

**Comment by NicoleTYF** [comment]
曱甴和在一起就是簡體字的國字，所以曱甴也比你愛國。你覺得這個邏輯怎樣？

**Comment by peachl** [comment]
> > wysnxzm 我祝福你說別人的東西會發生你身上。((或者是已經發生了？
> 
> 嗨,对于暴徒的任何诋毁我表示毫不在意
> 谁会在意一只曱甴的反抗呢?你得感谢有海关的存在,要不然第一天你们就被会丢进海里喂鱼
> 活在阴影下的宵小而已,连"革命"都不敢露出真面目,曱甴你们当之无愧
> 如果你们认为自己是正义的,为什么要把真面目隐藏在口罩之下?只有曱甴才见不得光不是吗

别和有认知障碍的人沟通了，这个人听不懂人话。只会胡搅蛮缠的。我觉得我对牛弹了一下午的琴。

**Comment by NicoleTYF** [comment]
> 嗨,对于暴徒的任何诋毁我表示毫不在意
> 谁会在意一只曱甴的反抗呢?你得感谢有海关的存在,要不然第一天你们就被会丢进海里喂鱼
> 活在阴影下的宵小而已,连"革命"都不敢露出真面目,曱甴你们当之无愧
> 如果你们认为自己是正义的,为什么要把真面目隐藏在口罩之下?只有曱甴才见不得光不是吗

那你覺的為什麼外交部那麼緊張說話？

**Comment by NicoleTYF** [comment]
peachl 那你開issue是來幹什麼？

**Comment by peachl** [comment]
> peachl 那你開issue是來幹什麼？

上一个和五常叫板的人叫卡扎菲。我希望你能一直硬气到外国人都撤侨完毕。顺带告诉你一下法国人打卡扎菲貌似是在中国人撤侨后。但是很可惜这次你们没有撤侨的参照目标了。祝你的运气和你的嘴巴一样铁。我都不准备理你了你还凑上来找不开心么？

**Comment by NicoleTYF** [comment]
@peachl 我也跟妳說，祝你的运气和你的嘴巴一样铁。我都不准备理你了你还凑上来找不开心么？

**Comment by peachl** [comment]
> @peachl 我也跟妳說，祝你的运气和你的嘴巴一样铁。我都不准备理你了你还凑上来找不开心么？

跳梁小丑

**Comment by NicoleTYF** [comment]
@peachl 我看來你們是來找開心的，也不是想要知識。

**Comment by NicoleTYF** [comment]
@peachl 你們說的，反過來就是你們在中國敢想不敢說的。

**Comment by peachl** [comment]
> @peachl 因為我看來你們是來找開心/發洩的（情緒化的字和標籤我們），也不是想要知識。

1start的你也好意思说这种话？怎么就这么坐井观天外加恬不知耻？

**Comment by wysnxzm** [comment]
> > @peachl 因為我看來你們是來找開心/發洩的（情緒化的字和標籤我們），也不是想要知識。
> 
> 1start的你也好意思说这种话？怎么就这么坐井观天外加恬不知耻？

确确实实是井底之蛙,没救的
不敢露脸的曱甴罢了,要是真的革命怎么要蒙面呢
一群被人利用的蠢蛋罢了

**Comment by NicoleTYF** [comment]
wysnxzm 那你去天安門革命給我看吧。你們越罵越想你們說別人的那樣，就像蘇聯解體前人民的瘋狂到意識不到自己是今天在歷史上的一點，『昨天蘇聯，今天中共』從習近平2018修憲法開始已經重演了。
