### ISSUE TITLE
英國劍橋大學突取消香港區面試，意味不收港生？

### ISSUE THREAD

**Issue by wysnxzm** [taibangle/awesome-china#16]
https://www.speakout.hk/%E6%B8%AF%E4%BA%BA%E8%8A%B1%E7%94%9F/50952/-%E9%BB%91%E6%9A%B4%E6%90%8D%E6%B8%AF%E8%81%B2%E8%AD%BD-%E8%8B%B1%E5%9C%8B%E5%8A%8D%E6%A9%8B%E5%A4%A7%E5%AD%B8%E7%AA%81%E5%8F%96%E6%B6%88%E9%A6%99%E6%B8%AF%E5%8D%80%E9%9D%A2%E8%A9%A6-%E6%84%8F%E5%91%B3%E4%B8%8D%E6%94%B6%E6%B8%AF%E7%94%9F-

**Comment by NicoleTYF** [comment]
@wysnxzm 『意味』倒是他自己看完猜測的，裏面說"further information will be sent to applicants once alternative interview arrangements will be made" 意思是Cambridge因為擔心學生的安全，可以透過alternative interview（另類面試方法）視像訪問/電話訪問取代現場面試，視像訪問/電話訪問最近也在商業界挺流行的。所以港人講地報導本身的小編是想多了，精神勝利不意外，你身為讀者不像他們捕風捉影就解決你的issue啦。

@MeiWithHongKong 這已經是網路騷擾了，你可以按他的id版面 點Block or report user，收集證據就行啦。

**Comment by wysnxzm** [comment]
> @wysnxzm 『意味』一詞看來是編輯自己看完猜測的。裏面說"further information will be sent to applicants once alternative interview arrangements will be made" 意思是Cambridge因為擔心學生的安全，可以透過alternative interview（另類面試方法）視像訪問/電話訪問取代現場面試，視像訪問/電話訪問最近也在商業界挺流行的。所以港人講地報導本身的小編是想多了，精神勝利不意外，你身為讀者不像他們捕風捉影就解決你的issue啦。

我只是转载个新闻啊你们不也是这么干的????双标圣母?
你们发新闻我们说过是假的你们不信现在你们解释谁听啊哈哈哈
这也太玻璃心了哈哈哈哈哈哈哈哈

**Comment by NicoleTYF** [comment]
那你開issue是來幹什麼，做小丑？

**Comment by wysnxzm** [comment]
> 那你開issue是來幹什麼，做小丑碰瓷？

你们能开project我就不能开issue?你们的民主和自由就是这样体现的?
你们能肆意发布不实新闻,我就不能转载新闻?
重新定义自由????民主????

**Comment by NicoleTYF** [comment]
那你說民主是不是中國特色主義的十二要素? 你是五毛一定很清楚啊

**Comment by wysnxzm** [comment]
> 那你說民主是不是中國特色主義的十二要素? 你是五毛一定很清楚啊.

?????你倒是说说为啥你们能开project我不能开issue的理由啊,自由和民主明显不行啊找个新的理由搞快点别转移话题

**Comment by NicoleTYF** [comment]
那你說民主是不是中國特色主義的十二要素? 你是五毛一定很清楚啊.

**Comment by NicoleTYF** [comment]
你常常笑別人啥，你覺得自己就是個笑話。你別傲嬌吧。

**Comment by NicoleTYF** [comment]
?????你不能開issue是因為你的騷擾別用家的行為是違反了 GitHub Community Guidelines 的規矩，違反了規矩就是濫用言論自由啊。

**Comment by wysnxzm** [comment]
> ?????你不能開issue是因為你的騷擾別用家的行為是違反了 GitHub Community Guidelines 的規矩，違反了規矩就是濫用言論自由啊。

哈哈哈哈哈解释不了民主自由就开始耍赖皮吗?
毫无逻辑的家伙,没意思
