### ISSUE TITLE
香港暴徒往无辜市民身上泼汽油点火，惨不忍睹，简直丧尽天良。

### ISSUE THREAD

**Issue by seamounts** [taibangle/awesome-china#18]

**Comment by NicoleTYF** [comment]
撑警灭废青！https://www.youtube.com/playlist?list=PLauVXX--jDm1EqSuC_TC5RQPnaiDCchPc

**Comment by NicoleTYF** [comment]
撑警灭废青！https://www.youtube.com/playlist?list=PLauVXX--jDm1EqSuC_TC5RQPnaiDCchPc
