### ISSUE TITLE
香港港大暴徒围殴内地学生，被打内地学生头破血流

### ISSUE THREAD

**Issue by seamounts** [taibangle/awesome-china#19]

**Comment by seamounts** [comment]
@MeiWithHongKong 交流一下吗，不要不说话。

**Comment by NicoleTYF** [comment]
多谢一直支持结束一党专政，多谢一直支持双普选，多谢一直给何韵诗点赞，多谢一直关注铜锣湾书店案，多谢一直声讨六四屠杀，多谢一直支持香港反送中，多谢一直支持劳工讨薪，你上次提供的关于中国制造业困局的资料非常有价值，万分感谢！

**Comment by NicoleTYF** [comment]
撑警灭废青！https://www.youtube.com/playlist?list=PLauVXX--jDm1EqSuC_TC5RQPnaiDCchPc

**Comment by NicoleTYF** [comment]
樓主交流一下吗，不要不说话。
