### ISSUE TITLE
香港暴徒阻碍交通，打砸过往车辆，导致香港普通市民出行受阻

### ISSUE THREAD

**Issue by seamounts** [taibangle/awesome-china#20]

**Comment by NicoleTYF** [comment]
親，多谢一直支持天安门母亲，多谢一直拥护司法独立，多谢一直支持维权律师，多谢一直支持双普选，多谢一直关注新疆集中营，多谢一直支持结束一党专政，多谢一直声讨六四屠杀，多谢一直关注北戴河会议，多谢一直为反送中发声，多谢一直支持香港反送中，多谢一直关注铜锣湾书店案，你上次提供的关于中国制造业困局的资料非常有价值，非常感谢！

**Comment by NicoleTYF** [comment]
撑警灭废青！https://www.youtube.com/playlist?list=PLauVXX--jDm1EqSuC_TC5RQPnaiDCchPc
