### ISSUE TITLE
年輕不好好奮鬥，卻以做漢奸為榮，歷史是怎麼學的，垃圾敗類？？？

### ISSUE THREAD

**Issue by Janyave** [taibangle/awesome-china#22]

**Comment by NicoleTYF** [comment]
親，多谢一直拥护司法独立，多谢一直支持结束一党专政，多谢一直关注新疆集中营，多谢一直支持劳工讨薪，多谢一直为反送中发声，多谢一直支持香港反送中，多谢一直给何韵诗点赞，你上次提供的关于08宪章的资料非常有价值，好人一生平安！

**Comment by NicoleTYF** [comment]
撑警灭废青！https://www.youtube.com/playlist?list=PLauVXX--jDm1EqSuC_TC5RQPnaiDCchPc

**Comment by NicoleTYF** [comment]
Janyave 你的標題是在罵自己嗎，罵得自己氣急敗壞似的。
